### PR TITLE
Add FTdx3000 driver file

### PR DESCRIPTION
**Pull request by mgrindle**
Let's see if this is OK

### CODE REVIEW

**Comment by mbalmer** [comment]
This looks good so far.  Did you test it and does it work?

**Comment by mgrindle** [comment]
Started testing. Corrected a syntax error (missing .) and pushed the change here. I figured out how to change the permissions on the ttyUSB . Determined that I needed to use ttyUSB0 to connect to the receiver. I was able to start trxd and trxctl in separate terminals. I could not get a command to be accepted by trxctl. This is what I tried:

$ trxctl
trxctl > {
  "request": "get-frequency"
}
no such command
trxctl > { "request": "get-frequency" }
no such command
trxctl > { "request": "trx-list" }
no such command
trxctl > {"request": "trx-list"}
no such command
trxctl > {"request":"trx-list"}
no such command
trxctl > 

Then I looked back at the trxd terminal and saw it had stopped.

$ trxd -d -l
dummy-trx: initialize
this is a Yaesu FTdx3000 transceiver
trxd[21604]: connection from 127.0.0.1
Segmentation fault (core dumped)
$ 

I then closed trxctl and re-started trxd and trxctl. I tried a command once more, no success. Looked back at trxd and it had stopped again with the seg fault. That is all I tried. 

What is the correct format for trxctl commands?

**Comment by mbalmer** [comment]
You must not manually enter JSON code, trxctl does that for your.  trx-control understands commands like set-frequency, get-frequency, set-mode, get-mode, start-status-updates etc.  It will then use NDJSON as the underlying protocol. See bin/trxctl/trxctl.c for the list of commands (starting on line 66).  Of course, these commands must eventually be documented in the trxctl(1) manual page.

**Comment by mbalmer** [comment]
Before this can be merged with the main branch, we need to ensure that we can at least set and get the frequency and mode.  When we are that point, it can go in.

**Comment by mbalmer** [comment]
The trxctl(1) commands have now been documented in the trxctl manual page.  Please update your repository.

**Comment by mgrindle** [comment]
I updated my repo with your latest changes and re-built everything. I like the man pages. I have not reviewed in detail yet but extremely helpful!

Below is the terminal output from my testing. Several commands error’ed out. The lock and unlock did work. Once locked, I could not change the frequency. I didn’t think to try to change bands however. The ‘set-frequency 7040000’ command responded with the frequency on the terminal but the radio remained on the existing frequency. 

The ‘start-status-updates’ command did not appear to do anything in the terminal. When I entered the ‘stop-status-updates’ command, trxctl appeared to hang-up and did not respond with a ‘trxctl >’.

I did not try the set-mode command correctly and it gave me an error.

Also, see at the bottom is the terminal output for trxd. There are some error messages.

$ trxctl 
trxctl > get-frequency 
trxctl > /usr/share/trxctl/trxctl.lua:104: attempt to index a nil value (local 'reply') 
trxctl > list-trx 
FTdx3000             yaesu-ftdx3000 on /dev/ttyUSB0 
Dummy                dummy-trx on /dev/null 
trxctl > get-mode 
trxctl > /usr/share/trxctl/trxctl.lua:130: attempt to index a nil value (local 'reply') 
trxctl > lock 
transceiver locked 
trxctl > unlock 
transceiver unlocked 
trxctl > set-frequency 
nil 
trxctl > set-frequency 7040000 
7040000 
trxctl > set-mode cw 
trxctl > /usr/share/trxctl/trxctl.lua:119: attempt to index a nil value (local 'reply') 
trxctl > start-status-updates 
trxctl > stop-status-updates 


$ trxd -d -l                   
dummy-trx: initialize 
this is a Yaesu FTdx3000 transceiver 
trxd[4663]: connection from 127.0.0.1 
trxd[4663]: Lua error: /usr/share/trxd/trx/yaesu-ft-710.lua:168: bad argument #1 to 'sub' (string expected, got nil) 
trxd[4663]: Lua error: /usr/share/trxd/trx/yaesu-ftdx3000.lua:95: bad argument #1 to 'for iterator' (table expected, got nil) 
FTdx3000        nil     nil 
trxd[4663]: Lua error: /usr/share/trxd/trx/yaesu-ftdx3000.lua:74: attempt to index a nil value (global 'validModes')

**Comment by mbalmer** [comment]
There is something wrong with your driver.  Compare it to the FT-817 or FT-710 driver, must be some detail

**Comment by mgrindle** [comment]
On the most basic level, I see the difference in the protocol for FT-817 (5 byte) vs FT-710 (using semicolon). From the official Yaesu document for FTdx3000 CAT control. It uses the semicolon version. So I'll look in more detail at the FT-710 driver and compare it to mine. If that fails,I might also try my original attempt (with the additions you've made) where I did not use 'require' to see if that might be the issue.

**Comment by mgrindle** [comment]
Attached are two files with the results of my testing the FTdx3000 driver
[2023-10-10-ftdx3000-driver.pdf](https://github.com/hb9ssb/trx-control/files/12894508/2023-10-10-ftdx3000-driver.pdf)
[2023-10-12-ftdx3000-driver.pdf](https://github.com/hb9ssb/trx-control/files/12894509/2023-10-12-ftdx3000-driver.pdf)

**Comment by mbalmer** [comment]
This driver is now incompatible with trx-control, please take a look at the FT-710 driver, it should now be a lot easier to adapt for the FTDX3000, as the protocols have been factored out.  A driver in most cases does not need a lot of code, but merely describes the transceiver.

**Pull request closed without merging**
