### PR TITLE
add trusdx driver and kenwood ts480 protocol.

### PR DESCRIPTION
**Pull request by gx1400**

### CODE REVIEW

**Comment by mbalmer** [comment]
This driver has issues:

- The trsudx driver defines filter sets, which are used nowhere, and they all have the same value which cannot be correct.
- The driver sets the capability "lock" true, but does not implement the lock/unlock functions.  Kenwook has the LK command for this.

Nitpicking, but..

- Between some words (in comments) are two spaces instead of one.
- Between some functions are two empty lines instead of one.

**Comment by gx1400** [comment]
For the lock/unlock functions, I took the lead of 

https://github.com/hb9ssb/trx-control/blob/main/protocol%2Fci-v.lua#L69

And created the function but did not implement it.

I do not see an example of any kind of "function not implemented" exception yet

**Comment by gx1400** [comment]
Additionally I do not see a get/set filter function impoemented in

https://github.com/hb9ssb/trx-control/blob/main/sbin%2Ftrxd%2Ftrx-controller.lua#L65

I'm not sure the trusdx implements that function, so maybe the validFilters should be removed?

**Comment by mbalmer** [comment]
Ok, I will merge this as is, so that we can continue to work on it.  Maybe it is needed to look at all drivers and to make things a bit consistent.

**Pull request merged**
