### PR TITLE
add ic7300 trx definition & modified ci-v file

### PR DESCRIPTION
**Pull request by gx1400**

### CODE REVIEW

**Comment by mbalmer** [comment]
I think this can not be a separate protocol.  CI-V is one protocol, if it is not able to drive a certain trx, the protocol must be ameliorated, but there is now way we have a receiver specific protocol.  Protocols are meant for a class of transceivers, not a specific transceiver.

**Comment by gx1400** [comment]
I understand.  When you have the time next week, I would like you to try to this protocol with your IC-705 and see if it is functional

**Comment by mbalmer** [comment]
Can you please provide a context diff against the current version of the ci-v protocol implementation, so that the changes are easier to spot?

**Comment by gx1400** [comment]
> Can you please provide a context diff against the current version of the ci-v protocol implementation, so that the changes are easier to spot?


[diff.pdf](https://github.com/hb9ssb/trx-control/files/14813381/diff.pdf)

I'm sorry, I'm struggling to find a good way to show compare.  I could also replace the ci-v.lua file and let the PR show the diff that way for evaluation

**Comment by mbalmer** [comment]
That is not a context diff.

**Comment by gx1400** [comment]
> That is not a context diff.

I apologize Marc. I merged ci-v-7300.lua into ci-v.lua to be one common protocol file.  I plan to go down to my radio this evening and verify the changes.

I do not have access to an IC-705 to understand how the ci-v differs.

The largest difference I think is that in my testing, I needed to read back the command 'ack' before being able to read the response.

1. trxd command 0x03 -> IC-7300
2. IC7300 0x03 ack -> trxd
3. IC7300 0x03 reply -> trxd

**Comment by gx1400** [comment]
I discovered my confusion.  Setting USB ECHO was on on my radio.  Refactoring

**Comment by gx1400** [comment]
cancelling PR

**Pull request closed without merging**
